#!/bin/sh

# Set -e to exit if any command fails
set -e

echo "Generating env.js from environment variables..."

# Path to the output env.js file (public so it's available to the frontend)
ENV_JS_PATH=/app/public/env.js

# Create the env.js file
cat <<EOF > $ENV_JS_PATH
window.__ENV__ = {
  NODE_ENV: "${NODE_ENV}",
  NEXT_PUBLIC_API_BASE_URL: "${NEXT_PUBLIC_API_BASE_URL}",
  NEXT_PUBLIC_LMS_URL: "${NEXT_PUBLIC_LMS_URL}",
  NEXT_PUBLIC_DM_URL_TEST: "${NEXT_PUBLIC_DM_URL_TEST}",
  NEXT_PUBLIC_AUTH_URL: "${NEXT_PUBLIC_AUTH_URL}",
  NEXT_PUBLIC_MFE_URL: "${NEXT_PUBLIC_MFE_URL}",
  NEXT_PUBLIC_STUDIO_URL: "${NEXT_PUBLIC_STUDIO_URL}",
  NEXT_PUBLIC_DISCOVER_FACETS_FILTERS_TO_HIDE: "${NEXT_PUBLIC_DISCOVER_FACETS_FILTERS_TO_HIDE}",
  NEXT_PUBLIC_HIDE_RECOMMENDED_TAB: "${NEXT_PUBLIC_HIDE_RECOMMENDED_TAB}",
  NEXT_PUBLIC_ENABLE_COURSE_ELIGIBILITY_LICENSE_CHECK: "${NEXT_PUBLIC_ENABLE_COURSE_ELIGIBILITY_LICENSE_CHECK}",
  NEXT_PUBLIC_ENABLE_START_ROLE: "${NEXT_PUBLIC_ENABLE_START_ROLE}",
  NEXT_PUBLIC_SPA_ANALYTICS_URL: "${NEXT_PUBLIC_SPA_ANALYTICS_URL}",
  NEXT_PUBLIC_USE_FOOTER_MENUS: "${NEXT_PUBLIC_USE_FOOTER_MENUS}",
  NEXT_PUBLIC_FOOTER_MENUS: "${NEXT_PUBLIC_FOOTER_MENUS}",
  NEXT_PUBLIC_COPYRIGHT: "${NEXT_PUBLIC_COPYRIGHT}",
  NEXT_PUBLIC_MENTOR_URL: "${NEXT_PUBLIC_MENTOR_URL}",
  NEXT_PUBLIC_ENABLE_MENTOR: "${NEXT_PUBLIC_ENABLE_MENTOR}",
  NEXT_PUBLIC_PLATFORM_BASE_DOMAIN: "${NEXT_PUBLIC_PLATFORM_BASE_DOMAIN}",
  NEXT_PUBLIC_ENABLE_RBAC: "${NEXT_PUBLIC_ENABLE_RBAC}",
  NEXT_PUBLIC_ENABLE_COMBINED_RECOMMENDATION_REPORT: "${NEXT_PUBLIC_ENABLE_COMBINED_RECOMMENDATION_REPORT}",
  NEXT_PUBLIC_COMBINED_RECOMMENDATION_REPORTS: "${NEXT_PUBLIC_COMBINED_RECOMMENDATION_REPORTS}",
  NEXT_PUBLIC_SUPPORT_EMAIL: "${NEXT_PUBLIC_SUPPORT_EMAIL}",
  NEXT_PUBLIC_HIDE_DISCOVER_TAB: "${NEXT_PUBLIC_HIDE_DISCOVER_TAB}",
  NEXT_PUBLIC_ADDITIONAL_LEFT_HEADER_MENU_ITEMS: "${NEXT_PUBLIC_ADDITIONAL_LEFT_HEADER_MENU_ITEMS}",
  NEXT_PUBLIC_ADDITIONAL_RIGHT_HEADER_MENU_ITEMS: "${NEXT_PUBLIC_ADDITIONAL_RIGHT_HEADER_MENU_ITEMS}",
  NEXT_PUBLIC_ENABLE_AI_ANALYTICS_HEADER_MENU: "${NEXT_PUBLIC_ENABLE_AI_ANALYTICS_HEADER_MENU}",
  NEXT_PUBLIC_ENABLE_STUDIO_HEADER_MENU: "${NEXT_PUBLIC_ENABLE_STUDIO_HEADER_MENU}",
  NEXT_PUBLIC_ENABLE_STATIC_COPYRIGHT: "${NEXT_PUBLIC_ENABLE_STATIC_COPYRIGHT}"
};
EOF

echo "env.js generated at $ENV_JS_PATH"

# Now start the Next.js app (adjust if you're using custom start scripts)
exec "$@" 